/**
 * AUTO-GENERATED by scripts/generate-kana-manifest-from-xlsx.ts
 * Source: docs/Asset N5.xlsx — do not edit by hand.
 * Re-run: bun run kana:generate
 */
export type KanaManifestScript = 'hiragana' | 'katakana';

export type KanaManifestEntry = {
  script: KanaManifestScript;
  category: string;
  char: string;
  romaji: string;
  vocabWord: string;
  vocabReading: string;
  vocabMeaning: string;
  strokeGifSrc: string;
};

export const KANA_MANIFEST: KanaManifestEntry[] = [
  {
    "script": "katakana",
    "category": "Dasar (Vokal)",
    "char": "ア",
    "romaji": "a",
    "vocabWord": "アイス",
    "vocabReading": "aisu",
    "vocabMeaning": "es krim",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30a2.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (Vokal)",
    "char": "イ",
    "romaji": "i",
    "vocabWord": "インク",
    "vocabReading": "inku",
    "vocabMeaning": "tinta",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30a4.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (Vokal)",
    "char": "ウ",
    "romaji": "u",
    "vocabWord": "ウイルス",
    "vocabReading": "uirusu",
    "vocabMeaning": "virus",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30a6.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (Vokal)",
    "char": "エ",
    "romaji": "e",
    "vocabWord": "エレベーター",
    "vocabReading": "erebeetaa",
    "vocabMeaning": "lift",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30a8.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (Vokal)",
    "char": "オ",
    "romaji": "o",
    "vocabWord": "オートバイ",
    "vocabReading": "ootobai",
    "vocabMeaning": "sepeda motor",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30aa.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (K)",
    "char": "カ",
    "romaji": "ka",
    "vocabWord": "カメラ",
    "vocabReading": "kamera",
    "vocabMeaning": "kamera",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ab.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (K)",
    "char": "キ",
    "romaji": "ki",
    "vocabWord": "キロ",
    "vocabReading": "kiro",
    "vocabMeaning": "kilo",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ad.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (K)",
    "char": "ク",
    "romaji": "ku",
    "vocabWord": "クラス",
    "vocabReading": "kurasu",
    "vocabMeaning": "kelas",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30af.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (K)",
    "char": "ケ",
    "romaji": "ke",
    "vocabWord": "ケーキ",
    "vocabReading": "keeki",
    "vocabMeaning": "kue",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b1.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (K)",
    "char": "コ",
    "romaji": "ko",
    "vocabWord": "コーヒー",
    "vocabReading": "koohii",
    "vocabMeaning": "kopi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b3.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (S)",
    "char": "サ",
    "romaji": "sa",
    "vocabWord": "サッカー",
    "vocabReading": "sakkaa",
    "vocabMeaning": "sepak bola",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b5.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (S)",
    "char": "シ",
    "romaji": "shi",
    "vocabWord": "シャツ",
    "vocabReading": "shatsu",
    "vocabMeaning": "kemeja",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b7.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (S)",
    "char": "ス",
    "romaji": "su",
    "vocabWord": "スープ",
    "vocabReading": "suupu",
    "vocabMeaning": "sup",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b9.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (S)",
    "char": "セ",
    "romaji": "se",
    "vocabWord": "セーター",
    "vocabReading": "seetaa",
    "vocabMeaning": "sweter",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30bb.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (S)",
    "char": "ソ",
    "romaji": "so",
    "vocabWord": "ソース",
    "vocabReading": "soosu",
    "vocabMeaning": "saus",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30bd.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (T)",
    "char": "タ",
    "romaji": "ta",
    "vocabWord": "タオル",
    "vocabReading": "taoru",
    "vocabMeaning": "handuk",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30bf.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (T)",
    "char": "チ",
    "romaji": "chi",
    "vocabWord": "チーズ",
    "vocabReading": "chiizu",
    "vocabMeaning": "keju",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c1.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (T)",
    "char": "ツ",
    "romaji": "tsu",
    "vocabWord": "ツアー",
    "vocabReading": "tsuaa",
    "vocabMeaning": "tur",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c4.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (T)",
    "char": "テ",
    "romaji": "te",
    "vocabWord": "テニス",
    "vocabReading": "tenisu",
    "vocabMeaning": "tenis",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c6.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (T)",
    "char": "ト",
    "romaji": "to",
    "vocabWord": "トマト",
    "vocabReading": "tomato",
    "vocabMeaning": "tomat",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c8.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (N)",
    "char": "ナ",
    "romaji": "na",
    "vocabWord": "ナイフ",
    "vocabReading": "naifu",
    "vocabMeaning": "pisau",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ca.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (N)",
    "char": "ニ",
    "romaji": "ni",
    "vocabWord": "ニット",
    "vocabReading": "nitto",
    "vocabMeaning": "rajutan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30cb.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (N)",
    "char": "ヌ",
    "romaji": "nu",
    "vocabWord": "ヌードル",
    "vocabReading": "nuudoru",
    "vocabMeaning": "mi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30cc.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (N)",
    "char": "ネ",
    "romaji": "ne",
    "vocabWord": "ネクタイ",
    "vocabReading": "nekutai",
    "vocabMeaning": "dasi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30cd.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (N)",
    "char": "ノ",
    "romaji": "no",
    "vocabWord": "ノート",
    "vocabReading": "nooto",
    "vocabMeaning": "buku catatan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ce.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (H)",
    "char": "ハ",
    "romaji": "ha",
    "vocabWord": "ハム",
    "vocabReading": "hamu",
    "vocabMeaning": "ham",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30cf.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (H)",
    "char": "ヒ",
    "romaji": "hi",
    "vocabWord": "ヒーター",
    "vocabReading": "hiitaa",
    "vocabMeaning": "pemanas",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d2.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (H)",
    "char": "フ",
    "romaji": "fu",
    "vocabWord": "フライパン",
    "vocabReading": "furaipan",
    "vocabMeaning": "wajan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d5.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (H)",
    "char": "ヘ",
    "romaji": "he",
    "vocabWord": "ヘリコプター",
    "vocabReading": "herikoputaa",
    "vocabMeaning": "helikopter",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d8.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (H)",
    "char": "ホ",
    "romaji": "ho",
    "vocabWord": "ホテル",
    "vocabReading": "hoteru",
    "vocabMeaning": "hotel",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30db.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (M)",
    "char": "マ",
    "romaji": "ma",
    "vocabWord": "マウス",
    "vocabReading": "mausu",
    "vocabMeaning": "mouse",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30de.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (M)",
    "char": "ミ",
    "romaji": "mi",
    "vocabWord": "ミルク",
    "vocabReading": "miruku",
    "vocabMeaning": "susu",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30df.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (M)",
    "char": "ム",
    "romaji": "mu",
    "vocabWord": "ムスリム",
    "vocabReading": "musurimu",
    "vocabMeaning": "muslim",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30e0.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (M)",
    "char": "メ",
    "romaji": "me",
    "vocabWord": "メロン",
    "vocabReading": "meron",
    "vocabMeaning": "melon",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30e1.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (M)",
    "char": "モ",
    "romaji": "mo",
    "vocabWord": "モーター",
    "vocabReading": "mootaa",
    "vocabMeaning": "motor",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30e2.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (Y)",
    "char": "ヤ",
    "romaji": "ya",
    "vocabWord": "タイヤ",
    "vocabReading": "taiya",
    "vocabMeaning": "ban",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30e4.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (Y)",
    "char": "ユ",
    "romaji": "yu",
    "vocabWord": "ユニフォーム",
    "vocabReading": "yunifoomu",
    "vocabMeaning": "seragam",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30e6.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (Y)",
    "char": "ヨ",
    "romaji": "yo",
    "vocabWord": "ヨーグルト",
    "vocabReading": "yooguruto",
    "vocabMeaning": "yogurt",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30e8.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (R)",
    "char": "ラ",
    "romaji": "ra",
    "vocabWord": "ラジオ",
    "vocabReading": "rajio",
    "vocabMeaning": "radio",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30e9.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (R)",
    "char": "リ",
    "romaji": "ri",
    "vocabWord": "リボン",
    "vocabReading": "ribon",
    "vocabMeaning": "pita",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ea.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (R)",
    "char": "ル",
    "romaji": "ru",
    "vocabWord": "ルール",
    "vocabReading": "ruuru",
    "vocabMeaning": "aturan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30eb.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (R)",
    "char": "レ",
    "romaji": "re",
    "vocabWord": "レストラン",
    "vocabReading": "resutoran",
    "vocabMeaning": "restoran",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ec.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (R)",
    "char": "ロ",
    "romaji": "ro",
    "vocabWord": "ロボット",
    "vocabReading": "robotto",
    "vocabMeaning": "robot",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ed.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (W)",
    "char": "ワ",
    "romaji": "wa",
    "vocabWord": "ワイン",
    "vocabReading": "wain",
    "vocabMeaning": "anggur",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ef.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (W)",
    "char": "ヲ",
    "romaji": "wo",
    "vocabWord": "ヲタク",
    "vocabReading": "wotaku",
    "vocabMeaning": "otaku - penulisan variasi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30f2.gif"
  },
  {
    "script": "katakana",
    "category": "Dasar (N/M/Ng)",
    "char": "ン",
    "romaji": "n",
    "vocabWord": "パン",
    "vocabReading": "pan",
    "vocabMeaning": "roti",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30f3.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (G)",
    "char": "ガ",
    "romaji": "ga",
    "vocabWord": "ガラス",
    "vocabReading": "garasu",
    "vocabMeaning": "kaca",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ac.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (G)",
    "char": "ギ",
    "romaji": "gi",
    "vocabWord": "ギター",
    "vocabReading": "gitaa",
    "vocabMeaning": "gitar",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ae.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (G)",
    "char": "グ",
    "romaji": "gu",
    "vocabWord": "グラス",
    "vocabReading": "gurasu",
    "vocabMeaning": "gelas",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b0.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (G)",
    "char": "ゲ",
    "romaji": "ge",
    "vocabWord": "ゲーム",
    "vocabReading": "geemu",
    "vocabMeaning": "gim/permainan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b2.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (G)",
    "char": "ゴ",
    "romaji": "go",
    "vocabWord": "ゴルフ",
    "vocabReading": "gorufu",
    "vocabMeaning": "golf",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b4.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (Z)",
    "char": "ザ",
    "romaji": "za",
    "vocabWord": "デザイン",
    "vocabReading": "dezain",
    "vocabMeaning": "desain",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b6.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (Z)",
    "char": "ジ",
    "romaji": "ji",
    "vocabWord": "ジーンズ",
    "vocabReading": "jiinzu",
    "vocabMeaning": "celana jeans",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b8.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (Z)",
    "char": "ズ",
    "romaji": "zu",
    "vocabWord": "ズーム",
    "vocabReading": "zuumu",
    "vocabMeaning": "zoom",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ba.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (Z)",
    "char": "ゼ",
    "romaji": "ze",
    "vocabWord": "ゼロ",
    "vocabReading": "zero",
    "vocabMeaning": "nol",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30bc.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (Z)",
    "char": "ゾ",
    "romaji": "zo",
    "vocabWord": "ゾーン",
    "vocabReading": "zoon",
    "vocabMeaning": "zona",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30be.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (D)",
    "char": "ダ",
    "romaji": "da",
    "vocabWord": "ダンス",
    "vocabReading": "dansu",
    "vocabMeaning": "dansa",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c0.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (D)",
    "char": "ヂ",
    "romaji": "ji",
    "vocabWord": "ヂーゼル",
    "vocabReading": "jiizeru",
    "vocabMeaning": "diesel - ejaan lama",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c2.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (D)",
    "char": "ヅ",
    "romaji": "zu",
    "vocabWord": "コヅカ",
    "vocabReading": "kozuka",
    "vocabMeaning": "pisau kecil - jarang",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c5.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (D)",
    "char": "デ",
    "romaji": "de",
    "vocabWord": "デパート",
    "vocabReading": "depaato",
    "vocabMeaning": "toserba",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c7.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (D)",
    "char": "ド",
    "romaji": "do",
    "vocabWord": "ドア",
    "vocabReading": "doa",
    "vocabMeaning": "pintu",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c9.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (B)",
    "char": "バ",
    "romaji": "ba",
    "vocabWord": "バナナ",
    "vocabReading": "banana",
    "vocabMeaning": "pisang",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d0.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (B)",
    "char": "ビ",
    "romaji": "bi",
    "vocabWord": "ビール",
    "vocabReading": "biiru",
    "vocabMeaning": "bir",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d3.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (B)",
    "char": "ブ",
    "romaji": "bu",
    "vocabWord": "ブレーキ",
    "vocabReading": "bureeki",
    "vocabMeaning": "rem",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d6.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (B)",
    "char": "ベ",
    "romaji": "be",
    "vocabWord": "ベッド",
    "vocabReading": "beddo",
    "vocabMeaning": "kasur",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d9.gif"
  },
  {
    "script": "katakana",
    "category": "Dakuon (B)",
    "char": "ボ",
    "romaji": "bo",
    "vocabWord": "ボタン",
    "vocabReading": "botan",
    "vocabMeaning": "tombol",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30dc.gif"
  },
  {
    "script": "katakana",
    "category": "Handakuon (P)",
    "char": "パ",
    "romaji": "pa",
    "vocabWord": "パーティー",
    "vocabReading": "paatii",
    "vocabMeaning": "pesta",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d1.gif"
  },
  {
    "script": "katakana",
    "category": "Handakuon (P)",
    "char": "ピ",
    "romaji": "pi",
    "vocabWord": "ピアノ",
    "vocabReading": "piano",
    "vocabMeaning": "piano",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d4.gif"
  },
  {
    "script": "katakana",
    "category": "Handakuon (P)",
    "char": "プ",
    "romaji": "pu",
    "vocabWord": "プール",
    "vocabReading": "puuru",
    "vocabMeaning": "kolam renang",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d7.gif"
  },
  {
    "script": "katakana",
    "category": "Handakuon (P)",
    "char": "ペ",
    "romaji": "pe",
    "vocabWord": "ペン",
    "vocabReading": "pen",
    "vocabMeaning": "pena",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30da.gif"
  },
  {
    "script": "katakana",
    "category": "Handakuon (P)",
    "char": "ポ",
    "romaji": "po",
    "vocabWord": "ポスト",
    "vocabReading": "posuto",
    "vocabMeaning": "kotak pos",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30dd.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (K)",
    "char": "キャ",
    "romaji": "kya",
    "vocabWord": "キャベツ",
    "vocabReading": "kyabetsu",
    "vocabMeaning": "kubis",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ad.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (K)",
    "char": "キュ",
    "romaji": "kyu",
    "vocabWord": "キューピッド",
    "vocabReading": "kyuupiddo",
    "vocabMeaning": "cupid",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ad.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (K)",
    "char": "キョ",
    "romaji": "kyo",
    "vocabWord": "トウキョウ",
    "vocabReading": "toukyou",
    "vocabMeaning": "Tokyo",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ad.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (S)",
    "char": "シャ",
    "romaji": "sha",
    "vocabWord": "シャワー",
    "vocabReading": "shawaa",
    "vocabMeaning": "shower",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b7.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (S)",
    "char": "シュ",
    "romaji": "shu",
    "vocabWord": "シューズ",
    "vocabReading": "shuuzu",
    "vocabMeaning": "sepatu",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b7.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (S)",
    "char": "ショ",
    "romaji": "sho",
    "vocabWord": "ショップ",
    "vocabReading": "shoppu",
    "vocabMeaning": "toko",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b7.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (T)",
    "char": "チャ",
    "romaji": "cha",
    "vocabWord": "チャンス",
    "vocabReading": "chansu",
    "vocabMeaning": "kesempatan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c1.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (T)",
    "char": "チュ",
    "romaji": "chu",
    "vocabWord": "チューブ",
    "vocabReading": "chuubu",
    "vocabMeaning": "tabung",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c1.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (T)",
    "char": "チョ",
    "romaji": "cho",
    "vocabWord": "チョコレート",
    "vocabReading": "chokoreeto",
    "vocabMeaning": "cokelat",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30c1.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (N)",
    "char": "ニャ",
    "romaji": "nya",
    "vocabWord": "ニャンコ",
    "vocabReading": "nyanko",
    "vocabMeaning": "kucing",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30cb.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (N)",
    "char": "ニュ",
    "romaji": "nyu",
    "vocabWord": "ニュース",
    "vocabReading": "nyuusu",
    "vocabMeaning": "berita",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30cb.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (N)",
    "char": "ニョ",
    "romaji": "nyo",
    "vocabWord": "ニョッキ",
    "vocabReading": "nyokki",
    "vocabMeaning": "gnocchi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30cb.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (H)",
    "char": "ヒャ",
    "romaji": "hya",
    "vocabWord": "ヒャク",
    "vocabReading": "hyaku",
    "vocabMeaning": "seratus - jarang katakana",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d2.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (H)",
    "char": "ヒュ",
    "romaji": "hyu",
    "vocabWord": "ヒューズ",
    "vocabReading": "hyuuzu",
    "vocabMeaning": "sekering",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d2.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (H)",
    "char": "ヒョ",
    "romaji": "hyo",
    "vocabWord": "ヒョウ",
    "vocabReading": "hyou",
    "vocabMeaning": "macan tutul",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d2.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (M)",
    "char": "ミャ",
    "romaji": "mya",
    "vocabWord": "ミャンマー",
    "vocabReading": "myanmaa",
    "vocabMeaning": "Myanmar",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30df.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (M)",
    "char": "ミュ",
    "romaji": "myu",
    "vocabWord": "ミュージック",
    "vocabReading": "myuujikku",
    "vocabMeaning": "musik",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30df.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (M)",
    "char": "ミョ",
    "romaji": "myo",
    "vocabWord": "ミョウガ",
    "vocabReading": "myouga",
    "vocabMeaning": "jahe Jepang",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30df.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (R)",
    "char": "リャ",
    "romaji": "rya",
    "vocabWord": "リャマ",
    "vocabReading": "ryama",
    "vocabMeaning": "llama",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ea.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (R)",
    "char": "リュ",
    "romaji": "ryu",
    "vocabWord": "リュック",
    "vocabReading": "ryukku",
    "vocabMeaning": "ransel",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ea.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (R)",
    "char": "リョ",
    "romaji": "ryo",
    "vocabWord": "マトリョーシカ",
    "vocabReading": "matoryooshika",
    "vocabMeaning": "matryoshka",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ea.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (G)",
    "char": "ギャ",
    "romaji": "gya",
    "vocabWord": "ギャング",
    "vocabReading": "gyangu",
    "vocabMeaning": "geng",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ae.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (G)",
    "char": "ギュ",
    "romaji": "gyu",
    "vocabWord": "レギュラー",
    "vocabReading": "regyuraa",
    "vocabMeaning": "reguler",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ae.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (G)",
    "char": "ギョ",
    "romaji": "gyo",
    "vocabWord": "ギョーザ",
    "vocabReading": "gyooza",
    "vocabMeaning": "pangsit",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30ae.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (J)",
    "char": "ジャ",
    "romaji": "ja",
    "vocabWord": "ジャム",
    "vocabReading": "jamu",
    "vocabMeaning": "selai",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b8.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (J)",
    "char": "ジュ",
    "romaji": "ju",
    "vocabWord": "ジュース",
    "vocabReading": "juusu",
    "vocabMeaning": "jus",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b8.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (J)",
    "char": "ジョ",
    "romaji": "jo",
    "vocabWord": "ジョギング",
    "vocabReading": "jogingu",
    "vocabMeaning": "lari pelan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30b8.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (B)",
    "char": "ビャ",
    "romaji": "bya",
    "vocabWord": "ビャクダン",
    "vocabReading": "byakudan",
    "vocabMeaning": "cendana",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d3.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (B)",
    "char": "ビュ",
    "romaji": "byu",
    "vocabWord": "ビュッフェ",
    "vocabReading": "byuffe",
    "vocabMeaning": "prasmanan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d3.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (B)",
    "char": "ビョ",
    "romaji": "byo",
    "vocabWord": "ビョウ",
    "vocabReading": "byou",
    "vocabMeaning": "paku payung",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d3.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (P)",
    "char": "ピャ",
    "romaji": "pya",
    "vocabWord": "ピャー",
    "vocabReading": "pyaa",
    "vocabMeaning": "suara melengking",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d4.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (P)",
    "char": "ピュ",
    "romaji": "pyu",
    "vocabWord": "コンピューター",
    "vocabReading": "konpyuutaa",
    "vocabMeaning": "komputer",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d4.gif"
  },
  {
    "script": "katakana",
    "category": "Yoon (P)",
    "char": "ピョ",
    "romaji": "pyo",
    "vocabWord": "ピョンピョン",
    "vocabReading": "pyonpyon",
    "vocabMeaning": "suara lompat",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/30d4.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (Vokal)",
    "char": "あ",
    "romaji": "a",
    "vocabWord": "あめ",
    "vocabReading": "ame",
    "vocabMeaning": "hujan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3042.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (Vokal)",
    "char": "い",
    "romaji": "i",
    "vocabWord": "いえ",
    "vocabReading": "ie",
    "vocabMeaning": "rumah",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3044.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (Vokal)",
    "char": "う",
    "romaji": "u",
    "vocabWord": "うし",
    "vocabReading": "ushi",
    "vocabMeaning": "sapi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3046.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (Vokal)",
    "char": "え",
    "romaji": "e",
    "vocabWord": "えき",
    "vocabReading": "eki",
    "vocabMeaning": "stasiun",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3048.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (Vokal)",
    "char": "お",
    "romaji": "o",
    "vocabWord": "おとこ",
    "vocabReading": "otoko",
    "vocabMeaning": "laki-laki",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304a.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (K)",
    "char": "か",
    "romaji": "ka",
    "vocabWord": "かさ",
    "vocabReading": "kasa",
    "vocabMeaning": "payung",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304b.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (K)",
    "char": "き",
    "romaji": "ki",
    "vocabWord": "きのう",
    "vocabReading": "kinou",
    "vocabMeaning": "kemarin",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304d.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (K)",
    "char": "く",
    "romaji": "ku",
    "vocabWord": "くつ",
    "vocabReading": "kutsu",
    "vocabMeaning": "sepatu",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304f.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (K)",
    "char": "け",
    "romaji": "ke",
    "vocabWord": "けむり",
    "vocabReading": "kemuri",
    "vocabMeaning": "asap",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3051.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (K)",
    "char": "こ",
    "romaji": "ko",
    "vocabWord": "こえ",
    "vocabReading": "koe",
    "vocabMeaning": "suara",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3053.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (S)",
    "char": "さ",
    "romaji": "sa",
    "vocabWord": "さかな",
    "vocabReading": "sakana",
    "vocabMeaning": "ikan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3055.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (S)",
    "char": "し",
    "romaji": "shi",
    "vocabWord": "しお",
    "vocabReading": "shio",
    "vocabMeaning": "garam",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3057.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (S)",
    "char": "す",
    "romaji": "su",
    "vocabWord": "すいか",
    "vocabReading": "suika",
    "vocabMeaning": "semangka",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3059.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (S)",
    "char": "せ",
    "romaji": "se",
    "vocabWord": "せかい",
    "vocabReading": "sekai",
    "vocabMeaning": "dunia",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/305b.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (S)",
    "char": "そ",
    "romaji": "so",
    "vocabWord": "そら",
    "vocabReading": "sora",
    "vocabMeaning": "langit",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/305d.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (T)",
    "char": "た",
    "romaji": "ta",
    "vocabWord": "たまご",
    "vocabReading": "tamago",
    "vocabMeaning": "telur",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/305f.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (T)",
    "char": "ち",
    "romaji": "chi",
    "vocabWord": "ちかてつ",
    "vocabReading": "chikatetsu",
    "vocabMeaning": "kereta bawah tanah",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3061.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (T)",
    "char": "つ",
    "romaji": "tsu",
    "vocabWord": "つき",
    "vocabReading": "tsuki",
    "vocabMeaning": "bulan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3064.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (T)",
    "char": "て",
    "romaji": "te",
    "vocabWord": "てがみ",
    "vocabReading": "tegami",
    "vocabMeaning": "surat",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3066.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (T)",
    "char": "と",
    "romaji": "to",
    "vocabWord": "とけい",
    "vocabReading": "tokei",
    "vocabMeaning": "jam",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3068.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (N)",
    "char": "な",
    "romaji": "na",
    "vocabWord": "なつ",
    "vocabReading": "natsu",
    "vocabMeaning": "musim panas",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/306a.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (N)",
    "char": "に",
    "romaji": "ni",
    "vocabWord": "にく",
    "vocabReading": "niku",
    "vocabMeaning": "daging",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/306b.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (N)",
    "char": "ぬ",
    "romaji": "nu",
    "vocabWord": "ぬの",
    "vocabReading": "nuno",
    "vocabMeaning": "kain",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/306c.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (N)",
    "char": "ね",
    "romaji": "ne",
    "vocabWord": "ねこ",
    "vocabReading": "neko",
    "vocabMeaning": "kucing",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/306d.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (N)",
    "char": "の",
    "romaji": "no",
    "vocabWord": "のみもの",
    "vocabReading": "nomimono",
    "vocabMeaning": "minuman",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/306e.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (H)",
    "char": "は",
    "romaji": "ha",
    "vocabWord": "はな",
    "vocabReading": "hana",
    "vocabMeaning": "bunga",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/306f.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (H)",
    "char": "ひ",
    "romaji": "hi",
    "vocabWord": "ひこうき",
    "vocabReading": "hikouki",
    "vocabMeaning": "pesawat",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3072.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (H)",
    "char": "ふ",
    "romaji": "fu",
    "vocabWord": "ふね",
    "vocabReading": "fune",
    "vocabMeaning": "kapal",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3075.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (H)",
    "char": "へ",
    "romaji": "he",
    "vocabWord": "へや",
    "vocabReading": "heya",
    "vocabMeaning": "kamar",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3078.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (H)",
    "char": "ほ",
    "romaji": "ho",
    "vocabWord": "ほし",
    "vocabReading": "hoshi",
    "vocabMeaning": "bintang",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/307b.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (M)",
    "char": "ま",
    "romaji": "ma",
    "vocabWord": "まど",
    "vocabReading": "mado",
    "vocabMeaning": "jendela",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/307e.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (M)",
    "char": "み",
    "romaji": "mi",
    "vocabWord": "みみ",
    "vocabReading": "mimi",
    "vocabMeaning": "telinga",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/307f.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (M)",
    "char": "む",
    "romaji": "mu",
    "vocabWord": "むし",
    "vocabReading": "mushi",
    "vocabMeaning": "serangga",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3080.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (M)",
    "char": "め",
    "romaji": "me",
    "vocabWord": "めがね",
    "vocabReading": "megane",
    "vocabMeaning": "kacamata",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3081.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (M)",
    "char": "も",
    "romaji": "mo",
    "vocabWord": "もも",
    "vocabReading": "momo",
    "vocabMeaning": "persik",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3082.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (Y)",
    "char": "や",
    "romaji": "ya",
    "vocabWord": "やま",
    "vocabReading": "yama",
    "vocabMeaning": "gunung",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3084.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (Y)",
    "char": "ゆ",
    "romaji": "yu",
    "vocabWord": "ゆき",
    "vocabReading": "yuki",
    "vocabMeaning": "salju",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3086.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (Y)",
    "char": "よ",
    "romaji": "yo",
    "vocabWord": "よる",
    "vocabReading": "yoru",
    "vocabMeaning": "malam",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3088.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (R)",
    "char": "ら",
    "romaji": "ra",
    "vocabWord": "らいおん",
    "vocabReading": "raion",
    "vocabMeaning": "singa",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3089.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (R)",
    "char": "り",
    "romaji": "ri",
    "vocabWord": "りんご",
    "vocabReading": "ringo",
    "vocabMeaning": "apel",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/308a.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (R)",
    "char": "る",
    "romaji": "ru",
    "vocabWord": "るす",
    "vocabReading": "rusu",
    "vocabMeaning": "tidak ada di rumah",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/308b.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (R)",
    "char": "れ",
    "romaji": "re",
    "vocabWord": "れきし",
    "vocabReading": "rekishi",
    "vocabMeaning": "sejarah",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/308c.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (R)",
    "char": "ろ",
    "romaji": "ro",
    "vocabWord": "ろうそく",
    "vocabReading": "rousoku",
    "vocabMeaning": "lilin",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/308d.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (W)",
    "char": "わ",
    "romaji": "wa",
    "vocabWord": "わたし",
    "vocabReading": "watashi",
    "vocabMeaning": "saya",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/308f.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (W)",
    "char": "を",
    "romaji": "wo",
    "vocabWord": "を",
    "vocabReading": "",
    "vocabMeaning": "Hanya dipakai sebagai partikel objek",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3092.gif"
  },
  {
    "script": "hiragana",
    "category": "Dasar (N/M/Ng)",
    "char": "ん",
    "romaji": "n",
    "vocabWord": "ほん",
    "vocabReading": "hon",
    "vocabMeaning": "buku",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3093.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (G)",
    "char": "が",
    "romaji": "ga",
    "vocabWord": "がっこう",
    "vocabReading": "gakkou",
    "vocabMeaning": "sekolah",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304c.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (G)",
    "char": "ぎ",
    "romaji": "gi",
    "vocabWord": "ぎんこう",
    "vocabReading": "ginkou",
    "vocabMeaning": "bank",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304e.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (G)",
    "char": "ぐ",
    "romaji": "gu",
    "vocabWord": "ぐあい",
    "vocabReading": "guai",
    "vocabMeaning": "kondisi/keadaan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3050.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (G)",
    "char": "げ",
    "romaji": "ge",
    "vocabWord": "げんき",
    "vocabReading": "genki",
    "vocabMeaning": "sehat",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3052.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (G)",
    "char": "ご",
    "romaji": "go",
    "vocabWord": "ごはん",
    "vocabReading": "gohan",
    "vocabMeaning": "nasi/makan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3054.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (Z)",
    "char": "ざ",
    "romaji": "za",
    "vocabWord": "ざっし",
    "vocabReading": "zasshi",
    "vocabMeaning": "majalah",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3056.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (Z)",
    "char": "じ",
    "romaji": "ji",
    "vocabWord": "じかん",
    "vocabReading": "jikan",
    "vocabMeaning": "waktu",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3058.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (Z)",
    "char": "ず",
    "romaji": "zu",
    "vocabWord": "ずぼん",
    "vocabReading": "zubon",
    "vocabMeaning": "celana panjang",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/305a.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (Z)",
    "char": "ぜ",
    "romaji": "ze",
    "vocabWord": "ぜんぶ",
    "vocabReading": "zenbu",
    "vocabMeaning": "semua",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/305c.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (Z)",
    "char": "ぞ",
    "romaji": "zo",
    "vocabWord": "ぞう",
    "vocabReading": "zou",
    "vocabMeaning": "gajah",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/305e.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (D)",
    "char": "だ",
    "romaji": "da",
    "vocabWord": "だいがく",
    "vocabReading": "daigaku",
    "vocabMeaning": "universitas",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3060.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (D)",
    "char": "ぢ",
    "romaji": "ji",
    "vocabWord": "はなぢ",
    "vocabReading": "hanaji",
    "vocabMeaning": "mimisan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3062.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (D)",
    "char": "づ",
    "romaji": "zu",
    "vocabWord": "つづく",
    "vocabReading": "tsuzuku",
    "vocabMeaning": "berlanjut",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3065.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (D)",
    "char": "で",
    "romaji": "de",
    "vocabWord": "でんわ",
    "vocabReading": "denwa",
    "vocabMeaning": "telepon",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3067.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (D)",
    "char": "ど",
    "romaji": "do",
    "vocabWord": "どあ",
    "vocabReading": "doa",
    "vocabMeaning": "pintu",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3069.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (B)",
    "char": "ば",
    "romaji": "ba",
    "vocabWord": "ばんごう",
    "vocabReading": "bangou",
    "vocabMeaning": "nomor",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3070.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (B)",
    "char": "び",
    "romaji": "bi",
    "vocabWord": "びじゅつかん",
    "vocabReading": "bijutsukan",
    "vocabMeaning": "museum seni",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3073.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (B)",
    "char": "ぶ",
    "romaji": "bu",
    "vocabWord": "ぶた",
    "vocabReading": "buta",
    "vocabMeaning": "babi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3076.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (B)",
    "char": "べ",
    "romaji": "be",
    "vocabWord": "べんきょう",
    "vocabReading": "benkyou",
    "vocabMeaning": "belajar",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3079.gif"
  },
  {
    "script": "hiragana",
    "category": "Dakuon (B)",
    "char": "ぼ",
    "romaji": "bo",
    "vocabWord": "ぼうし",
    "vocabReading": "boushi",
    "vocabMeaning": "topi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/307c.gif"
  },
  {
    "script": "hiragana",
    "category": "Handakuon (P)",
    "char": "ぱ",
    "romaji": "pa",
    "vocabWord": "ぱん",
    "vocabReading": "pan",
    "vocabMeaning": "roti",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3071.gif"
  },
  {
    "script": "hiragana",
    "category": "Handakuon (P)",
    "char": "ぴ",
    "romaji": "pi",
    "vocabWord": "ぴかぴか",
    "vocabReading": "pikapika",
    "vocabMeaning": "mengkilap",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3074.gif"
  },
  {
    "script": "hiragana",
    "category": "Handakuon (P)",
    "char": "ぷ",
    "romaji": "pu",
    "vocabWord": "ぷん",
    "vocabReading": "pun",
    "vocabMeaning": "menit - akhiran",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3077.gif"
  },
  {
    "script": "hiragana",
    "category": "Handakuon (P)",
    "char": "ぺ",
    "romaji": "pe",
    "vocabWord": "ぺこぺこ",
    "vocabReading": "pekopeko",
    "vocabMeaning": "lapar/suara perut",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/307a.gif"
  },
  {
    "script": "hiragana",
    "category": "Handakuon (P)",
    "char": "ぽ",
    "romaji": "po",
    "vocabWord": "ぽすと",
    "vocabReading": "posuto",
    "vocabMeaning": "kotak pos",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/307d.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (K)",
    "char": "きゃ",
    "romaji": "kya",
    "vocabWord": "きゃく",
    "vocabReading": "kyaku",
    "vocabMeaning": "tamu",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304d.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (K)",
    "char": "きゅ",
    "romaji": "kyu",
    "vocabWord": "きゅうり",
    "vocabReading": "kyuuri",
    "vocabMeaning": "mentimun",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304d.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (K)",
    "char": "きょ",
    "romaji": "kyo",
    "vocabWord": "きょう",
    "vocabReading": "kyou",
    "vocabMeaning": "hari ini",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304d.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (S)",
    "char": "しゃ",
    "romaji": "sha",
    "vocabWord": "しゃしん",
    "vocabReading": "shashin",
    "vocabMeaning": "foto",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3057.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (S)",
    "char": "しゅ",
    "romaji": "shu",
    "vocabWord": "しゅくだい",
    "vocabReading": "shukudai",
    "vocabMeaning": "pekerjaan rumah",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3057.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (S)",
    "char": "しょ",
    "romaji": "sho",
    "vocabWord": "しょくどう",
    "vocabReading": "shokudou",
    "vocabMeaning": "kantin",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3057.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (T)",
    "char": "ちゃ",
    "romaji": "cha",
    "vocabWord": "ちゃいろ",
    "vocabReading": "chairo",
    "vocabMeaning": "warna cokelat",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3061.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (T)",
    "char": "ちゅ",
    "romaji": "chu",
    "vocabWord": "ちゅうしゃ",
    "vocabReading": "chuusha",
    "vocabMeaning": "suntikan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3061.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (T)",
    "char": "ちょ",
    "romaji": "cho",
    "vocabWord": "ちょきん",
    "vocabReading": "chokin",
    "vocabMeaning": "tabungan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3061.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (N)",
    "char": "にゃ",
    "romaji": "nya",
    "vocabWord": "にゃんこ",
    "vocabReading": "nyanko",
    "vocabMeaning": "kucing - kasual",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/306b.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (N)",
    "char": "にゅ",
    "romaji": "nyu",
    "vocabWord": "にゅうがく",
    "vocabReading": "nyuugaku",
    "vocabMeaning": "masuk sekolah",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/306b.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (N)",
    "char": "にょ",
    "romaji": "nyo",
    "vocabWord": "にょうぼう",
    "vocabReading": "nyoubou",
    "vocabMeaning": "istri",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/306b.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (H)",
    "char": "ひゃ",
    "romaji": "hya",
    "vocabWord": "ひゃく",
    "vocabReading": "hyaku",
    "vocabMeaning": "seratus",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3072.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (H)",
    "char": "ひゅ",
    "romaji": "hyu",
    "vocabWord": "ひゅうひゅう",
    "vocabReading": "hyuuhyuu",
    "vocabMeaning": "suara angin",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3072.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (H)",
    "char": "ひょ",
    "romaji": "hyo",
    "vocabWord": "ひょう",
    "vocabReading": "hyou",
    "vocabMeaning": "macan tutul / tabel",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3072.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (M)",
    "char": "みゃ",
    "romaji": "mya",
    "vocabWord": "みゃく",
    "vocabReading": "myaku",
    "vocabMeaning": "denyut nadi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/307f.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (M)",
    "char": "みゅ",
    "romaji": "myu",
    "vocabWord": "みゅーじっく",
    "vocabReading": "myuujikku",
    "vocabMeaning": "musik",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/307f.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (M)",
    "char": "みょ",
    "romaji": "myo",
    "vocabWord": "みょうじ",
    "vocabReading": "myouji",
    "vocabMeaning": "nama keluarga",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/307f.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (R)",
    "char": "りゃ",
    "romaji": "rya",
    "vocabWord": "りゃくご",
    "vocabReading": "ryakugo",
    "vocabMeaning": "singkatan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/308a.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (R)",
    "char": "りゅ",
    "romaji": "ryu",
    "vocabWord": "りゅう",
    "vocabReading": "ryuu",
    "vocabMeaning": "naga",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/308a.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (R)",
    "char": "りょ",
    "romaji": "ryo",
    "vocabWord": "りょこう",
    "vocabReading": "ryokou",
    "vocabMeaning": "wisata",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/308a.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (G)",
    "char": "ぎゃ",
    "romaji": "gya",
    "vocabWord": "ぎゃく",
    "vocabReading": "gyaku",
    "vocabMeaning": "kebalikan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304e.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (G)",
    "char": "ぎゅ",
    "romaji": "gyu",
    "vocabWord": "ぎゅうにゅう",
    "vocabReading": "gyuunyuu",
    "vocabMeaning": "susu sapi",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304e.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (G)",
    "char": "ぎょ",
    "romaji": "gyo",
    "vocabWord": "きんぎょ",
    "vocabReading": "kingyo",
    "vocabMeaning": "ikan mas koki",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/304e.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (J)",
    "char": "じゃ",
    "romaji": "ja",
    "vocabWord": "じゃま",
    "vocabReading": "jama",
    "vocabMeaning": "gangguan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3058.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (J)",
    "char": "じゅ",
    "romaji": "ju",
    "vocabWord": "じゅぎょう",
    "vocabReading": "jugyou",
    "vocabMeaning": "pelajaran",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3058.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (J)",
    "char": "じょ",
    "romaji": "jo",
    "vocabWord": "じょせい",
    "vocabReading": "josei",
    "vocabMeaning": "perempuan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3058.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (B)",
    "char": "びゃ",
    "romaji": "bya",
    "vocabWord": "さんびゃく",
    "vocabReading": "sanbyaku",
    "vocabMeaning": "tiga ratus",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3073.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (B)",
    "char": "びゅ",
    "romaji": "byu",
    "vocabWord": "びゅんびゅん",
    "vocabReading": "byunbyun",
    "vocabMeaning": "melesat cepat",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3073.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (B)",
    "char": "びょ",
    "romaji": "byo",
    "vocabWord": "びょういん",
    "vocabReading": "byouin",
    "vocabMeaning": "rumah sakit",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3073.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (P)",
    "char": "ぴゃ",
    "romaji": "pya",
    "vocabWord": "ろっぴゃく",
    "vocabReading": "roppyaku",
    "vocabMeaning": "enam ratus",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3074.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (P)",
    "char": "ぴゅ",
    "romaji": "pyu",
    "vocabWord": "ぴゅーぴゅー",
    "vocabReading": "pyuupyuu",
    "vocabMeaning": "suara tiupan",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3074.gif"
  },
  {
    "script": "hiragana",
    "category": "Yoon (P)",
    "char": "ぴょ",
    "romaji": "pyo",
    "vocabWord": "はっぴょう",
    "vocabReading": "happyou",
    "vocabMeaning": "pengumuman",
    "strokeGifSrc": "https://raw.githubusercontent.com/mistval/kanji_images/master/gifs/3074.gif"
  }
];

