export const OFFICIAL_COURSE_V1_SHEET_ALIASES = {
  course: ['Course', '1. Course'],
  module: ['Module', '2. Module'],
  lesson: ['Lesson', '3. Lesson'],
  video: ['Video', '4. Video'],
  text: ['Text', '5. Text'],
  flashcard: ['Flashcard', '6. Flashcard'],
  quiz: ['Quiz', '7. Quiz'],
} as const;

/** Normalized header keys produced by `normalizeHeaderKey` from Indonesian column titles. */
export const OFFICIAL_COURSE_V1_HEADERS = {
  course: ['id_eksternal_kursus', 'judul'],
  module: ['id_eksternal_modul', 'id_eksternal_kursus', 'judul', 'urutan'],
  lesson: ['id_eksternal_pelajaran', 'id_eksternal_modul', 'judul', 'urutan', 'tipe_pelajaran'],
  video: ['id_eksternal_pelajaran', 'url_video'],
  text: ['id_eksternal_pelajaran', 'teks_konten'],
  flashcard: ['id_eksternal_pelajaran', 'track'],
  quiz: ['id_eksternal_pelajaran', 'pertanyaan', 'pilihan_jawaban', 'jawaban_benar'],
} as const;

export const OFFICIAL_COURSE_V1_FIELDS = {
  courseExternalId: 'id_eksternal_kursus',
  moduleExternalId: 'id_eksternal_modul',
  lessonExternalId: 'id_eksternal_pelajaran',
  title: 'judul',
  slug: 'slug_url',
  description: 'deskripsi',
  level: 'level',
  published: 'publikasi',
  order: 'urutan',
  lessonType: 'tipe_pelajaran',
  videoUrl: 'url_video',
  textContent: 'teks_konten',
  track: 'track',
  category: 'kategori',
  flashcardTerm: 'huruf_kosakata_tata_bahasa',
  furigana: 'furigana',
  romaji: 'romaji',
  meaning: 'arti',
  onyomi: 'romaji_onyomi',
  kunyomi: 'romaji_kunyomi',
  exampleOnyomi: 'contoh_kata_onyomi',
  meaningOnyomi: 'arti_onyomi',
  exampleKunyomi: 'contoh_kata_kunyomi',
  meaningKunyomi: 'arti_kunyomi',
  mnemonic: 'mnemonik',
  strokeGifUrl: 'gif_cara_menulis_kanji',
  exampleSentence: 'contoh_kalimat',
  grammar: 'tata_bahasa',
  vocabulary: 'kosakata',
  question: 'pertanyaan',
  options: 'pilihan_jawaban',
  correctAnswer: 'jawaban_benar',
  explanation: 'penjelasan',
} as const;
