/**
 * Generate `features/kana/lib/kana-manifest.generated.ts` from docs/Asset N5.xlsx.
 *
 * Sheet titles for Hiragana/Katakana are swapped relative to cell content —
 * script is detected from Unicode of the character, not the sheet name.
 *
 * Usage: bun run kana:generate
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import ExcelJS from 'exceljs';

const ROOT = join(import.meta.dir, '..');
const XLSX_PATH = join(ROOT, 'docs', 'Asset N5.xlsx');
const OUT_PATH = join(ROOT, 'features', 'kana', 'lib', 'kana-manifest.generated.ts');

type KanaScript = 'hiragana' | 'katakana';

type KanaManifestEntry = {
  script: KanaScript;
  category: string;
  char: string;
  romaji: string;
  vocabWord: string;
  vocabReading: string;
  vocabMeaning: string;
  strokeGifSrc: string;
};

const KANA_SHEET_MARKERS = ['らがな', 'タカナ', 'hiragana', 'katakana'] as const;

function isKanaSheetName(name: string): boolean {
  const lower = name.toLowerCase();
  return KANA_SHEET_MARKERS.some((m) => name.includes(m) || lower.includes(m));
}

function detectScript(char: string): KanaScript | null {
  const cp = char.codePointAt(0);
  if (cp == null) return null;
  if (cp >= 0x3040 && cp <= 0x309f) return 'hiragana';
  if (cp >= 0x30a0 && cp <= 0x30ff) return 'katakana';
  return null;
}

function cellText(value: ExcelJS.CellValue): string {
  if (value == null) return '';
  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
    return String(value).trim();
  }
  if (typeof value === 'object' && 'text' in value && typeof value.text === 'string') {
    return value.text.trim();
  }
  if (typeof value === 'object' && 'result' in value && value.result != null) {
    return String(value.result).trim();
  }
  if (typeof value === 'object' && 'hyperlink' in value) {
    const rich = value as ExcelJS.CellHyperlinkValue;
    if (typeof rich.text === 'string') return rich.text.trim();
    if (typeof rich.hyperlink === 'string') return rich.hyperlink.trim();
  }
  return String(value).trim();
}

/** Parse `aisu (es krim)` → { reading, meaning } */
export function parseRomajiAndMeaning(raw: string): { reading: string; meaning: string } {
  const trimmed = raw.trim();
  const match = trimmed.match(/^(.*?)\s*\((.*)\)\s*$/);
  if (!match) {
    return { reading: trimmed, meaning: '' };
  }
  return { reading: match[1].trim(), meaning: match[2].trim() };
}

function parseSheet(ws: ExcelJS.Worksheet): KanaManifestEntry[] {
  const entries: KanaManifestEntry[] = [];

  ws.eachRow({ includeEmpty: false }, (row, rowNumber) => {
    if (rowNumber === 1) return;

    const category = cellText(row.getCell(2).value);
    const char = cellText(row.getCell(3).value);
    const romaji = cellText(row.getCell(4).value).toLowerCase();
    const vocabWord = cellText(row.getCell(5).value);
    const romajiArti = cellText(row.getCell(6).value);
    let strokeGifSrc = cellText(row.getCell(7).value);

    const gifCell = row.getCell(7);
    if (gifCell.hyperlink) {
      strokeGifSrc = String(gifCell.hyperlink).trim();
    } else if (
      gifCell.value &&
      typeof gifCell.value === 'object' &&
      'hyperlink' in gifCell.value &&
      typeof (gifCell.value as ExcelJS.CellHyperlinkValue).hyperlink === 'string'
    ) {
      strokeGifSrc = (gifCell.value as ExcelJS.CellHyperlinkValue).hyperlink.trim();
    }

    if (!char || !romaji || !category) return;

    const script = detectScript(char);
    if (!script) {
      console.warn(`[kana-manifest] skip unknown script char: ${char}`);
      return;
    }

    const { reading, meaning } = parseRomajiAndMeaning(romajiArti);

    entries.push({
      script,
      category,
      char,
      romaji,
      vocabWord,
      vocabReading: reading,
      vocabMeaning: meaning,
      strokeGifSrc,
    });
  });

  return entries;
}

async function main() {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(XLSX_PATH);

  const entries: KanaManifestEntry[] = [];

  for (const ws of workbook.worksheets) {
    if (!isKanaSheetName(ws.name)) continue;
    const parsed = parseSheet(ws);
    console.log(`[kana-manifest] ${ws.name}: ${parsed.length} rows`);
    entries.push(...parsed);
  }

  const hiragana = entries.filter((e) => e.script === 'hiragana');
  const katakana = entries.filter((e) => e.script === 'katakana');
  console.log(`[kana-manifest] totals — hiragana: ${hiragana.length}, katakana: ${katakana.length}`);

  if (hiragana.length === 0 || katakana.length === 0) {
    throw new Error('Expected both hiragana and katakana entries from Asset N5.xlsx');
  }

  const body = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-kana-manifest-from-xlsx.ts
 * Source: docs/Asset N5.xlsx — do not edit by hand.
 * Re-run: bun run kana:generate
 */
export type KanaManifestScript = 'hiragana' | 'katakana';

export type KanaManifestEntry = {
  script: KanaManifestScript;
  category: string;
  char: string;
  romaji: string;
  vocabWord: string;
  vocabReading: string;
  vocabMeaning: string;
  strokeGifSrc: string;
};

export const KANA_MANIFEST: KanaManifestEntry[] = ${JSON.stringify(entries, null, 2)};
`;

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, `${body}\n`, 'utf8');
  console.log(`[kana-manifest] wrote ${OUT_PATH}`);
}

await main();
