/**
 * Generate `features/kana/lib/kana-manifest.generated.ts` from docs/Asset N5.xlsx.
 *
 * Sheet titles for Hiragana/Katakana are swapped relative to cell content —
 * script is detected from Unicode of the character, not the sheet name.
 *
 * Usage: bun run kana:generate
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import * as XLSX from 'xlsx';

const ROOT = join(import.meta.dir, '..');
const XLSX_PATH = join(ROOT, 'docs', 'Asset N5.xlsx');
const OUT_PATH = join(ROOT, 'features', 'kana', 'lib', 'kana-manifest.generated.ts');

type KanaScript = 'hiragana' | 'katakana';

type KanaManifestEntry = {
  script: KanaScript;
  category: string;
  char: string;
  romaji: string;
  vocabWord: string;
  vocabReading: string;
  vocabMeaning: string;
  strokeGifSrc: string;
};

const KANA_SHEET_MARKERS = ['らがな', 'タカナ', 'hiragana', 'katakana'] as const;

function isKanaSheetName(name: string): boolean {
  const lower = name.toLowerCase();
  return KANA_SHEET_MARKERS.some((m) => name.includes(m) || lower.includes(m));
}

function detectScript(char: string): KanaScript | null {
  const cp = char.codePointAt(0);
  if (cp == null) return null;
  if (cp >= 0x3040 && cp <= 0x309f) return 'hiragana';
  if (cp >= 0x30a0 && cp <= 0x30ff) return 'katakana';
  return null;
}

/** Parse `aisu (es krim)` → { reading, meaning } */
export function parseRomajiAndMeaning(raw: string): { reading: string; meaning: string } {
  const trimmed = raw.trim();
  const match = trimmed.match(/^(.*?)\s*\((.*)\)\s*$/);
  if (!match) {
    return { reading: trimmed, meaning: '' };
  }
  return { reading: match[1].trim(), meaning: match[2].trim() };
}

function parseSheet(ws: XLSX.WorkSheet): KanaManifestEntry[] {
  const rows = XLSX.utils.sheet_to_json<(string | number)[]>(ws, {
    header: 1,
    defval: '',
  });
  const entries: KanaManifestEntry[] = [];

  for (let i = 1; i < rows.length; i++) {
    const row = rows[i];
    if (!row) continue;
    const category = String(row[1] ?? '').trim();
    const char = String(row[2] ?? '').trim();
    const romaji = String(row[3] ?? '').trim().toLowerCase();
    const vocabWord = String(row[4] ?? '').trim();
    const romajiArti = String(row[5] ?? '').trim();
    const strokeGifSrc = String(row[6] ?? '').trim();

    if (!char || !romaji || !category) continue;

    const script = detectScript(char);
    if (!script) {
      console.warn(`[kana-manifest] skip unknown script char: ${char}`);
      continue;
    }

    const { reading, meaning } = parseRomajiAndMeaning(romajiArti);

    entries.push({
      script,
      category,
      char,
      romaji,
      vocabWord,
      vocabReading: reading,
      vocabMeaning: meaning,
      strokeGifSrc,
    });
  }

  return entries;
}

function main() {
  const wb = XLSX.readFile(XLSX_PATH);
  const entries: KanaManifestEntry[] = [];

  for (const name of wb.SheetNames) {
    if (!isKanaSheetName(name)) continue;
    const ws = wb.Sheets[name];
    if (!ws) continue;
    const parsed = parseSheet(ws);
    console.log(`[kana-manifest] ${name}: ${parsed.length} rows`);
    entries.push(...parsed);
  }

  const hiragana = entries.filter((e) => e.script === 'hiragana');
  const katakana = entries.filter((e) => e.script === 'katakana');
  console.log(`[kana-manifest] totals — hiragana: ${hiragana.length}, katakana: ${katakana.length}`);

  if (hiragana.length === 0 || katakana.length === 0) {
    throw new Error('Expected both hiragana and katakana entries from Asset N5.xlsx');
  }

  const body = `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-kana-manifest-from-xlsx.ts
 * Source: docs/Asset N5.xlsx — do not edit by hand.
 * Re-run: bun run kana:generate
 */
export type KanaManifestScript = 'hiragana' | 'katakana';

export type KanaManifestEntry = {
  script: KanaManifestScript;
  category: string;
  char: string;
  romaji: string;
  vocabWord: string;
  vocabReading: string;
  vocabMeaning: string;
  strokeGifSrc: string;
};

export const KANA_MANIFEST: KanaManifestEntry[] = ${JSON.stringify(entries, null, 2)};
`;

  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, `${body}\n`, 'utf8');
  console.log(`[kana-manifest] wrote ${OUT_PATH}`);
}

main();
